# Logs
logs
*.log
npm-debug.log" ggg
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
npm-debug.log*
hi
npm-debug.log*
lnpm-debug.log*
erna-debug.log* hii
lnpm-debug.log*

hi
hi


# Runtime data

# Diagnostic reports (https://nodejs.org/api/report.html)

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
hi

# Runtime data
# Runtime data
# Runtime data
hgjkh

pids
ppp
*.pid
*.seed
hi
*.seed

*.seed
*.pid.lock

# Runtime data
hi
*.pid.lock  hi

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul

# Coverage directory used by tools like istanbul

hi 
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration

# node-waf configuration
.lock-wscript
hi

# node-waf configuration

jii
# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache!
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/
.rts2_cache_umd/
khi
# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity
# Yarn Integrity file
ho
# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next
.next
hi
# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories

# Serverless directories
.serverless/
# Serverless directories
hji

# FuseBox cache
.fusebox/
# FuseBox cache
hi
# DynamoDB Local files
.dynamodb/
# TernJS port file
hji
# TernJS port file
.tern-port
# TernJS port file
# TernJS port file
hi# TernJS port file
hi

hi
# macOS
.DS_Store

# python
pycache/

# Ignore .husky for new contributors using lefthook while maintaining
# backwards compatibility for past contributors
.husky


# VSCode
.vscode/launch.json
packages/protocol/config.js
.vercel

ho
